# config.yml

backend:
  name: github
  repo: animguild/animguild.github.io
  branch: dev-content
media_folder: 'assets/uploads'
collections:
  - name: 'courses'
    label: 'Courses'
    folder: '_courses/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'course' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Image Size', name: 'imageSize', widget: 'select', options: [ 'large', 'medium', 'full' ], default: 'medium' }
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false }
      - { label: 'Stripe Price Id', name: 'price_id', widget: 'string', hint: 'price_1I0DJxAllhMShDXbvnRRBPyW' }
      - { label: 'Stripe Price Id (Test)', name: 'price_id_test', widget: 'string', hint: 'price_1I0DJxAllhMShDXbvnRRBPyW' }
      - { label: 'Price', name: 'price', widget: 'number', min: 0, value_type: 'float' }
      - { label: 'Start Date', name: 'start_date', widget: 'datetime', date_format: 'DD.MM.YYYY' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, hint: 'comma separated tags' }
      - {
        label: 'Mentors',
        name: 'mentors',
        widget: 'relation',
        collection: 'mentors',
        multiple: true,
        required: false,
        display_fields: [ 'display_name' ],
        search_fields: [ 'display_name' ],
        value_field: 'name',
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'mentors'
    label: 'Mentors'
    folder: '_mentors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'mentor' }
      - { label: 'Name', name: 'display_name', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Image Size', name: 'imageSize', widget: 'select', options: [ 'large', 'medium', 'full' ], default: 'medium' }
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 3, hint: 'Higher numbers show towards the top' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Body', name: 'body', widget: 'markdown' }